[[plugins]]
repo = 'Shougo/echodoc'
on_i = 1

[[plugins]]
repo = 'Shougo/vimshell'
on_cmd = ['VimShell', 'VimShellExecute', 'VimShellInteractive','VimShellTerminal', 'VimShellPop']
on_map = ['<Plug>(vimfiler_switch)']

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'deris/vim-duzzle'
on_cmd = 'DuzzleStart'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'

[[plugins]]
repo = 'jceb/vim-orgmode'
on_ft = 'org'

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = 'blade'

[[plugins]]
repo = 'katono/rogue.vim'
on_cmd = ['Rogue', 'RogueRestore']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'lambdalisue/vim-gita'
on_cmd = ['Gita']

[[plugins]]
repo = 'lambdalisue/guise.vim'
on_ft = 'terminal'
on_source = 'denops.vim'

[[plugins]]
repo = 'lambdalisue/vim-manpager'
on_cmd = ['ASMANPAGER', 'Man']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'
on_ft = 'vue'
hook_add = '''
let g:vim_vue_plugin_config = {
   \ 'syntax': {
   \    'template': ['html'],
   \    'script': ['typescript'],
   \    'style': ['css', 'scss', 'sass', 'less'],
   \    'i18n': ['json', 'yaml'],
   \    'route': 'json',
   \ },
   \ 'full_syntax': ['json'],
   \ 'initial_indent': ['i18n', 'i18n.json', 'yaml'],
   \ 'attribute': 1,
   \ 'keyword': 1,
   \ 'foldexpr': 1,
   \ 'debug': 0,
   \ }
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_icon_indent = ["\Uf3100\Uf3102 ", "\Uf3101\Uf3102 "]
let g:vista#renderer#icons = {
  \ 'func':           "\Uff794",
  \ 'function':       "\Uff794",
  \ 'functions':      "\Uff794",
  \ 'var':            "\Uff71b",
  \ 'variable':       "\Uff71b",
  \ 'variables':      "\Uff71b",
  \ 'const':          "\Uff8ff",
  \ 'constant':       "\Uff8ff",
  \ 'method':         "\Uff6a6",
  \ 'package':        "\Ufe612",
  \ 'packages':       "\Ufe612",
  \ 'enum':           "\Uff435",
  \ 'enumerator':     "\Uff435",
  \ 'module':         "\Uff668",
  \ 'modules':        "\Uff668",
  \ 'type':           "\Ufe22b",
  \ 'typedef':        "\Ufe22b",
  \ 'types':          "\Ufe22b",
  \ 'field':          "\Uff93d",
  \ 'fields':         "\Uff93d",
  \ 'macro':          "\Uff8a3",
  \ 'macros':         "\Uff8a3",
  \ 'map':            "\Uffb44",
  \ 'class':          "\Uff9a9",
  \ 'augroup':        "\Uffb44",
  \ 'struct':         "\Uffb44",
  \ 'union':          "\Uffacd",
  \ 'member':         "\Uff02b",
  \ 'target':         "\Uff893",
  \ 'property':       "\Uffab6",
  \ 'interface':      "\Uffa52",
  \ 'namespace':      "\Uff475",
  \ 'subroutine':     "\Uff915",
  \ 'implementation': "\Uff87a",
  \ 'typeParameter':  "\Uff278",
  \ 'default':        "\Uff29c"
  \ }
'''

[[plugins]]
repo = 'mattn/benchvimrc-vim'
on_cmd = 'BenchVimrc'

[[plugins]]
repo = 'mattn/flappyvird-vim'
on_cmd = 'FlappyVird'

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_cmd = 'Template'

[[plugins]]
repo = 'mattn/wwwrenderer-vim'
depends = ['webapi-vim']

[[plugins]]
repo = 'mkusher/padawan.vim'
on_ft = 'php'

[[plugins]]
repo = 'nelsyeung/twig.vim'
on_ft= 'twig'

[[plugins]]
repo = 'osyo-manga/vim-marching'
depends = ['vimproc.vim', 'vim-reunions']
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'

[[plugins]]
repo = 'osyo-manga/vim-snowdrop'
on_ft = 'cpp'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'thinca/vim-ft-clojure'
on_ft = 'clojure'

[[plugins]]
repo = 'thinca/vim-github'
on_cmd = 'Github'

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_cmd = ['PP', 'PrettyPrint']

[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = ['Ref', 'RefHistory']

[[plugins]]
repo = 'thinca/vim-textobj-function-javascript'
depends = ['vim-textobj-function']
on_ft = 'javascript'

[[plugins]]
repo = 'thinca/vim-threes'
on_cmd = 'ThreesStart'

[[plugins]]
repo = 'tobyS/vmustache'
on_ft = 'vim'

[[plugins]]
repo = 'tobyS/pdv'
on_ft = 'php'

[[plugins]]
repo = 'tpope/vim-cucumber'
on_ft = 'cucumber'

[[plugins]]
repo = 'tsukkee/lingr-vim'
on_cmd = 'LingrLaunch'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neoclojure.vim'
on_ft = 'clojure'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'
depends = ['vimshell']
on_ft = 'vimshell'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'vim-jp/vital.vim'
on_cmd = ['Vitalize']
on_ft = 'vim'

[[plugins]]
repo = 'yoppi/fluentd.vim'
on_ft = 'fluentd'

[[plugins]]
repo = 'yuratomo/w3m.vim'
on_cmd = ['W3m', 'W3mTab']
if = '''executable('w3m')'''
