[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
nnoremap <silent> ,g  <Cmd>Ddu
  \ -name=search rg
  \ -source-param-input=`input('Pattern: ')`<CR>
nnoremap <silent> ,cg <Cmd>Ddu
  \ -name=search rg -source-param-input=`expand('<cword>')`
  \ -ui-param-startFilter=v:false<CR>
nnoremap <silent> ,r <Cmd>Ddu
  \ -name=search -resume
  \ -ui-param-startFilter=v:false<CR>
'''
hook_source = '''
call ddu#custom#patch_global({
  \   'ui': 'ff',
  \   'sourceOptions': {
  \     '_': {
  \       'matchers': ['matcher_fzf', 'matcher_substring'],
  \     },
  \   },
  \   'kindOptions': {
  \     'file': {
  \       'defaultAction': 'open',
  \     },
  \   },
  \   'sourceParams': {
  \     'rg': {
  \       'args': ['--column', '--no-heading', '--color', 'always']
  \     }
  \   }
  \ })
call ddu#custom#patch_local('files', {
  \   'uiParams': {
  \     'ff': {
  \       'split': has('nvim') ? 'floating' : 'horizontal',
  \     }
  \   },
  \ })
'''

[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
  \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> <C-l>
  \ <Cmd>call ddu#ui#ff#do_action('refreshItems')<CR>
nnoremap <buffer><silent> p
  \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer><silent> a
  \ <Cmd>call ddu#ui#ff#do_action('chooseAction')<CR>
nnoremap <buffer><silent> c
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'cd'})<CR>
nnoremap <buffer><silent> d
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'delete'})<CR>
nnoremap <buffer><silent> e
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'edit'})<CR>
nnoremap <buffer><silent> v
  \ <Cmd>call ddu#ui#ff#do_action('itemAction',
  \ {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> N
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'new'})<CR>
nnoremap <buffer><silent> r
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'quickfix'})<CR>
nnoremap <buffer><silent> u
  \ <Cmd>call ddu#ui#ff#do_action('updateOptions', {
  \   'sourceOptions': {
  \     '_': {
  \       'matchers': [],
  \     },
  \   },
  \ })<CR>
'''
ddu-ff-filter = '''
inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

