[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  call denite#custom#option('_', 'statusline', v:false)
'''

[[plagins]]
repo = 'Shougo/deoppet.nvim'
if = '''has('nvim')'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet', 'deoppet.nvim']

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'cohama/agit.vim'
  
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = '''has('python')'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
  
[[plugins]]
repo = 'joonty/vdebug'
if = '''has('python')'''

[[plugins]]
repo = 'justinmk/vim-dirvish'
  
[[plugins]]
repo = 'kakkyz81/evervim'
if = '''has('python')'''

[[plugins]]
repo = 'kamichidu/vim-ref-java'
depends = ['wwwrenderer-vim']

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'lambdalisue/vim-unified-diff'

[[plugins]]
repo = 'machakann/vim-swap'

[[plugins]]
repo = 'mattn/libcallex-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'miyakogi/conoline.vim'

[[plugins]]
repo = 'osyo-manga/quickrun-hook-u-nya-'
depends = ['vim-quickrun']

[[plugins]]
repo = 'osyo-manga/quickrun-hook-vcvarsall'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'osyo-manga/vim-reunions'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['typescript-vim']

[[plugins]]
repo = 'rbtnn/game_engine.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-singleton'

[[plugins]]
repo = 'thinca/vim-splash'

[[plugins]]
repo = 'ujihisa/neco-look'
if = '''executable('look')'''

[[plugins]]
repo = 'yaasita/slack.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
