[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
nnoremap <silent> ,g  <Cmd>Ddu
  \ -name=search rg
  \ -source-param-rg-input=`input('Pattern: ')`<CR>
nnoremap <silent> ,cg <Cmd>Ddu
  \ -name=search rg
  \ -source-param-rg-input=`expand('<cword>')`
  \ -ui-param-ff-startFilter=v:false<CR>
nnoremap <silent> ,r <Cmd>Ddu
  \ -name=search -resume
  \ -ui-param-ff-startFilter=v:false<CR>
'''
hook_source = '''
call ddu#custom#patch_global({
  \   'ui': 'ff',
  \   'sourceOptions': {
  \     '_': {
  \       'matchers': ['matcher_fzf', 'matcher_substring'],
  \     },
  \     'dein_update': {
  \       'matchers': ['matcher_dein_update'],
  \     },
  \     'file_rec': {
  \       'converters': [{'name': 'converter_hl_dir'}],
  \     },
  \   },
  \   'kindOptions': {
  \     'file': {
  \       'defaultAction': 'open',
  \     },
  \     'custom-list': {
  \       'defaultAction': 'callback',
  \     },
  \     'dein_update': {
  \       'matchers': 'viewDiff',
  \     },
  \     'lsp_codeAction': {
  \       'defaultAction': 'apply',
  \     },
  \   },
  \   'sourceParams': {
  \     'rg': {
  \       'args': ['--json']
  \     },
  \     'ddu_update': {
  \       'useGraphQL': v:true,
  \     },
  \   },
  \   'uiParams': {
  \     'ff': {
  \       'autoAction': {
  \         'name': 'preview',
  \       },
  \       'previewFloating': v:true,
  \       'previewHeight': 40,
  \       'split': 'horizontal',
  \       'prompt': '> '
  \     },
  \   },
  \ })
call ddu#custom#set_local('file', {
  \   'uiParams': {
  \     'ff': {
  \       'floatingTitle': 'file',
  \     },
  \   },
  \ })
call ddu#custom#set_local('lsp', {
  \   'uiParams': {
  \     'ff': {
  \       'floatingTitle': 'lsp',
  \     },
  \   },
  \ })
'''

[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>
  \ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> <C-l>
  \ <Cmd>call ddu#ui#do_action('refreshItems')<CR>
nnoremap <buffer><silent> p
  \ <Cmd>call ddu#ui#do_action('togglePreview')<CR>
nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
nnoremap <buffer><silent> a
  \ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
nnoremap <buffer><silent> c
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'cd'})<CR>
nnoremap <buffer><silent> d
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'delete'})<CR>
nnoremap <buffer><silent> e
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'edit'})<CR>
nnoremap <buffer><silent> v
  \ <Cmd>call ddu#ui#do_action('itemAction',
  \ {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
nnoremap <buffer><silent> N
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'new'})<CR>
nnoremap <buffer><silent> r
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'quickfix'})<CR>
nnoremap <buffer><silent> u
  \ <Cmd>call ddu#ui#do_action('updateOptions', {
  \   'sourceOptions': {
  \     '_': {
  \       'matchers': [],
  \     },
  \   },
  \ })<CR>
'''
ddu-ff-filter = '''
inoremap <buffer> <CR>
  \ <Esc><Cmd>call ddu#ui#do_action('itemAction')<CR>
inoremap <buffer> <C-f>
  \ <Cmd>call ddu#ui#do_action('cursorNext', {'loop': v:true})<CR>
inoremap <buffer> <C-b>
  \ <Cmd>call ddu#ui#do_action('cursorPrevious', {'loop': v:true})<CR>
inoremap <buffer> <C-v>
  \ <Cmd>call ddu#ui#do_action('toggleAutoAction')<CR>
nnoremap <buffer> <C-n>
  \ <Cmd>call ddu#ui#do_action('cursorNext', {'loop': v:true})<CR>
nnoremap <buffer> <C-p>
  \ <Cmd>call ddu#ui#do_action('cursorPrevious', {'loop': v:true})<CR>
nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
nnoremap <buffer> P
  \ <Cmd>call ddu#ui#do_action('togglePreview')<CR>
nnoremap <buffer> a
  \ <Cmd>call ddu#ui#do_action('chooseAction')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kamecha/ddu-source-floaterm'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
on_source = 'ddu.vim'
hook_add = '''
command! DduDeinUpdate :Ddu dein_update
'''

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'
hook_add = '''
let g:ddu_source_lsp_clientName = 'vim-lsp'
'''

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'
